"""add shipping address to orders

Revision ID: r1s2t3u4v5w6
Revises: 73f7ed383a45
Create Date: 2026-08-25

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'r1s2t3u4v5w6'
down_revision: Union[str, None] = '73f7ed383a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_full_name', sa.String(length=120), nullable=True))
    op.add_column('orders', sa.Column('shipping_phone', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('shipping_line1', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_line2', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_state', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_zip', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('shipping_country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'shipping_zip')
    op.drop_column('orders', 'shipping_state')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_line2')
    op.drop_column('orders', 'shipping_line1')
    op.drop_column('orders', 'shipping_phone')
    op.drop_column('orders', 'shipping_full_name')
    # ### end Alembic commands ###
