"""add stub support tables

Revision ID: u6v7w8x9y0z1
Revises: t2u3v4w5x6y7
Create Date: 2026-08-26 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'u6v7w8x9y0z1'
down_revision = 't2u3v4w5x6y7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'training_assessment_submissions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('training_id', sa.UUID(), nullable=False),
        sa.Column('assessment_id', sa.VARCHAR(), nullable=False),
        sa.Column('participant_email', sa.VARCHAR(length=255), nullable=False),
        sa.Column('answers', sa.JSON(), nullable=False),
        sa.Column('score', sa.INTEGER(), nullable=True),
        sa.Column('passed', sa.BOOLEAN(), nullable=True),
        sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['training_id'], ['trainings.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'training_assignment_submissions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('training_id', sa.UUID(), nullable=False),
        sa.Column('assignment_id', sa.VARCHAR(), nullable=False),
        sa.Column('participant_email', sa.VARCHAR(length=255), nullable=False),
        sa.Column('file_url', sa.TEXT(), nullable=True),
        sa.Column('submission_text', sa.TEXT(), nullable=True),
        sa.Column('grade', sa.INTEGER(), nullable=True),
        sa.Column('feedback', sa.TEXT(), nullable=True),
        sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['training_id'], ['trainings.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'training_progress',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('training_id', sa.UUID(), nullable=False),
        sa.Column('participant_email', sa.VARCHAR(length=255), nullable=False),
        sa.Column('sections_completed', sa.JSON(), nullable=True),
        sa.Column('lessons_completed', sa.JSON(), nullable=True),
        sa.Column('overall_percent', sa.FLOAT(), nullable=True),
        sa.Column('certificate_url', sa.TEXT(), nullable=True),
        sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('last_accessed_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['training_id'], ['trainings.id']),
        sa.UniqueConstraint('training_id', 'participant_email'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'training_live_sessions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('training_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.VARCHAR(length=255), nullable=False),
        sa.Column('description', sa.TEXT(), nullable=True),
        sa.Column('scheduled_at', sa.TIMESTAMP(), nullable=False),
        sa.Column('duration_minutes', sa.INTEGER(), nullable=True),
        sa.Column('meeting_link', sa.TEXT(), nullable=True),
        sa.Column('meeting_provider', sa.VARCHAR(length=50), nullable=True),
        sa.Column('status', sa.VARCHAR(length=20), nullable=True),
        sa.Column('recording_url', sa.TEXT(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['training_id'], ['trainings.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'program_surveys',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('program_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.VARCHAR(length=255), nullable=False),
        sa.Column('description', sa.TEXT(), nullable=True),
        sa.Column('questions', sa.JSON(), nullable=False),
        sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
        sa.Column('is_active', sa.BOOLEAN(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['program_id'], ['programs.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'program_reviews',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('program_id', sa.UUID(), nullable=False),
        sa.Column('participant_email', sa.VARCHAR(length=255), nullable=False),
        sa.Column('rating', sa.INTEGER(), nullable=False),
        sa.Column('comment', sa.TEXT(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['program_id'], ['programs.id']),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_reviews')
    op.drop_table('program_surveys')
    op.drop_table('training_live_sessions')
    op.drop_table('training_progress')
    op.drop_table('training_assignment_submissions')
    op.drop_table('training_assessment_submissions')